### ISSUE TITLE
Alternative config format for sequencing data

### ISSUE THREAD

**Issue by iskandr** [openvax/neoantigen-vaccine-pipeline#118]
Move `type: paired-end` to top-level `sequencing-read-type` or some other similar name. Could also optionally have it per normal/tumor/RNA in case those end up being different for some reason, but seem unnecessary to have it for each "fragment". 

Also, anything we do to hide the term "fragment" from the user would be good, since it's confusing the context of sequencing. 

One possibility, instead of 

```
rna:
    - fragment_id: L001
      type: paired-end
      r1: /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001_R1_001.fastq.gz
      r2: /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001_R2_001.fastq.gz
    - fragment_id: L002
      type: paired-end
      r1: /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002_R1_001.fastq.gz
      r2: /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002_R2_001.fastq.gz
```

have:

```
rna:
    type: paired-end
    files: 
       L001:
           - /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001_R1_001.fastq.gz
          - /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L001_R2_001.fastq.gz
      L002:
          - /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002_R1_001.fastq.gz
          - /inputs/pgv001-018/TD00410_PGV001_018_RNA/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002/PGV001_018_TU_RNA_01_01_CAGATC_HKTYNBCX2_L002_R2_001.fastq.gz
```
